### ISSUE TITLE
List dependency requirements for Java

### ISSUE THREAD

**Issue by laurikimmel** [infostellarinc/stellarstation-api#171]
While upgrading stellarstation-api version from 0.2.0 to 0.3.0 I saw some unexpected exceptions. Upgrading other GRPC related dependencies fixed my tests.

Relevant version updates
```
com.stellarstation.api:stellarstation-api:0.2.0 -> 0.3.0
com.google.auth:google-auth-library-oauth2-http:0.11.0 -> 0.16.2
io.grpc:grpc-auth:1.16.1 -> 1.21.0
io.grpc:grpc-netty:1.16.1 -> 1.21.0
io.grpc:grpc-protobuf:1.16.1 -> 1.21.0
io.grpc:grpc-stub:1.16.1 -> 1.21.0
io.netty:netty-tcnative-boringssl-static:2.0.17.Final -> 2.0.25.Final
``` 

Example stacktrace
```
ERROR 45310 --- [ault-executor-0] io.grpc.internal.ManagedChannelImpl      : [Channel<1>: (192.168.99.100:32799)] Uncaught exception in the SynchronizationContext. Panic!

java.lang.AbstractMethodError: io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.newClientTransport(Ljava/net/SocketAddress;Lio/grpc/internal/ClientTransportFactory$ClientTransportOptions;Lio/grpc/ChannelLogger;)Lio/grpc/internal/ConnectionClientTransport;
	at io.grpc.internal.CallCredentialsApplyingTransportFactory.newClientTransport(CallCredentialsApplyingTransportFactory.java:49) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:266) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.InternalSubchannel.obtainActiveTransport(InternalSubchannel.java:216) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.ManagedChannelImpl$SubchannelImpl.requestConnection(ManagedChannelImpl.java:1510) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.PickFirstLoadBalancer.handleResolvedAddressGroups(PickFirstLoadBalancer.java:59) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.handleResolvedAddressGroups(AutoConfiguredLoadBalancerFactory.java:150) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl$1NamesResolved.run(ManagedChannelImpl.java:1385) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:88) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:120) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl.onAddresses(ManagedChannelImpl.java:1391) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:305) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:214) [grpc-core-1.20.0.jar:1.20.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

ERROR 45310 --- [ault-executor-0] stellarstation.ConnectionHandler  : onError: io.grpc.StatusRuntimeException

io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.grpc.Status.asRuntimeException(Status.java:532) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434) [grpc-stub-1.16.1.jar:1.16.1]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:398) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.20.0.jar:1.20.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: java.lang.AbstractMethodError: io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.newClientTransport(Ljava/net/SocketAddress;Lio/grpc/internal/ClientTransportFactory$ClientTransportOptions;Lio/grpc/ChannelLogger;)Lio/grpc/internal/ConnectionClientTransport;
	at io.grpc.internal.CallCredentialsApplyingTransportFactory.newClientTransport(CallCredentialsApplyingTransportFactory.java:49) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:266) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.InternalSubchannel.obtainActiveTransport(InternalSubchannel.java:216) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.ManagedChannelImpl$SubchannelImpl.requestConnection(ManagedChannelImpl.java:1510) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.PickFirstLoadBalancer.handleResolvedAddressGroups(PickFirstLoadBalancer.java:59) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.handleResolvedAddressGroups(AutoConfiguredLoadBalancerFactory.java:150) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl$1NamesResolved.run(ManagedChannelImpl.java:1385) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:88) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:120) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl.onAddresses(ManagedChannelImpl.java:1391) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:305) ~[grpc-core-1.20.0.jar:1.20.0]
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:214) ~[grpc-core-1.20.0.jar:1.20.0]
	... 3 common frames omitted
```

**Comment by laurikimmel** [comment]
Upgrading stellarstation-api version form 0.3.0 to 0.4.0 didn't reveal any issues - same dependency versions are working fine.

**Comment by gavinreaney** [comment]
Thanks for reporting this, and apologies for the slow response. We'll be more careful about this in our future releases (basically our pre-release testing wasn't thorough enough on this occasion).
