### ISSUE TITLE
Fakeserver Docker image outdated

### ISSUE THREAD

**Issue by laurikimmel** [infostellarinc/stellarstation-api#29]
1. I'm not able to find any ```Dockerfile``` from the repo
2. When I try to run fakeserver as Docker container
```
$ docker run -p 8080:8080 -p 8081:8081 -it --rm quay.io/infostellarinc/fake-apiserver
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/stellarstation/api/fakeserver/FakeServerMain has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```
3. Fakeserver is using ```stellarstation-api:0.0.2```. Latest release at the moment is ```0.0.8```.
4. Current fakeserver Docker image is huge
```
$ docker image ls | grep fake-apiserver
quay.io/infostellarinc/fake-apiserver   latest              694c1171d2df        7 weeks ago         706MB
```
Could you consider using smaller base image? For example ```openjdk:8-jre-alpine``` or ```openjdk:10-jre-slim``` would produce several hundred MBs smaller results.

**Comment by anuraaga** [comment]
Thanks a lot for reporting! Indeed the base image is completely wrong, I have just pushed an updated image which should run and be much smaller.

**Comment by laurikimmel** [comment]
Looks better now. No exceptions on startup and Docker image is much smaller

```
$ docker image ls | grep fake-apiserver
quay.io/infostellarinc/fake-apiserver   latest              9fa5083790aa        About an hour ago   368MB
```
